# Generated by Django 3.2 on 2023-03-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herculesbankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='number_of_transfer',
            field=models.FloatField(default=0, null=True),
        ),
    ]
